/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.*;
import java.util.*;

/**
 *
 * @author B1
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    public Print() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnrec = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtarearcip = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        btnrec.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnrec.setText("Recipet");
        btnrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnexit.setForeground(new java.awt.Color(51, 51, 51));
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnrec)
                .addGap(72, 72, 72)
                .addComponent(btnexit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrec)
                    .addComponent(btnexit))
                .addGap(28, 28, 28))
        );

        jtxtarearcip.setBackground(new java.awt.Color(204, 255, 204));
        jtxtarearcip.setColumns(20);
        jtxtarearcip.setRows(5);
        jtxtarearcip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jScrollPane1.setViewportView(jtxtarearcip);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Receive print");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecActionPerformed
//          Calendar timer =Calendar.getInstance();
//        timer.getTime();
//        SimpleDateFormat tTime= new SimpleDateFormat("HH:mm:ss");
//       String iTime=(tTime.format(timer.getTime()));
//       //SimpleDateFormat.tDate = new SimpleDateFormat("dd-MMM-YYYY");
//       //String iDate = (tDate.format(timer.getTime()));
//       int num1;
//       String ref= "";
//       num1= 100+(int)(Math.random()*4000);
//       ref+=num1+100;
//       String FirstName = (.getText());
//       String LastName = (jtxtLastName.getText());
//       String Address = (jtxtAddress.getText());
//       String Email = (jtxtEmail.getText());
//       String Mobile = (jtxtMobile.getText());
//       String SubTotal=(jtxtSubTotal.getText());
//       String Tax=(jtxtTax.getText());
//       String Total=(jtxtTotal.getText());
//       jtxtAreaReceipt.append("\t Sopno Vubon:\n\n"+"Reference:\t\t\t"+ref
//               +"\n-----------------"
//               +"\nFirstName:\t\t\t" + FirstName
//               +"\nLastName:\t\t\t" +LastName
//               +"\nAddress:\t\t\t" +Address
//               +"\nEmail:\t\t\t" +Email 
//               +"\nTax:\t\t\t"+ Tax
//
//               +"\nMobile:\t\t\t" +Mobile
//               +"\nSubTotal:\t\t\t" + SubTotal
//               +"\nTax:\t\t\t"+ Tax
//               +"\nTotal:\t\t\t" + Total
//               +"\n-------------"
//              // +"\nDate:"+iDate 
//               +"\nTime:" +iTime
//               +"\n\n\n\n\n\nThanks for stay with Sopno Vubon"
//               +"\nHave a happy and safe journey"       
//       );
    }//GEN-LAST:event_btnrecActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    
    
     public void displayAll(String cls_id,String clsname,String totalseat,String fillup,String blank){
         
         
         
     
     
     
//       Calendar timer =Calendar.getInstance();
//        timer.getTime();
//        SimpleDateFormat tTime= new SimpleDateFormat("HH:mm:ss");
//       String iTime=(tTime.format(timer.getTime()));
//       SimpleDateFormat.tDate = new SimpleDateFormat("dd-MMM-YYYY");
//       String iDate = (tDate.format(timer.getTime()));
//       int num1;
//       String ref= "";
//       num1= 100+(int)(Math.random()*4000);
//       ref+=num1+100;
//        cls_id = (txtcid.getText());
//        clsname = (cmbclas.getSelectedItem().toString());
//        totalseat  = (.getText());
//       fillup = (txtseat.getText());
//        blank = (txtblank.getText());
//       String SubTotal=(jtxtSubTotal.getText());
//       String Tax=(jtxtTax.getText());
//       String Total=(jtxtTotal.getText());
       jtxtarearcip.append("\t total seat:\n\n"+"Reference:\t\t\t"
               +"\n-----------------"
               +"\nFirstName:\t\t\t" + cls_id
               +"\nLastName:\t\t\t" +clsname
               +"\nAddress:\t\t\t" +totalseat
               +"\nEmail:\t\t\t" +fillup
               +"\nTax:\t\t\t"+ blank

//               +"\nMobile:\t\t\t" +Mobile
//               +"\nSubTotal:\t\t\t" + SubTotal
//               +"\nTax:\t\t\t"+ Tax
//               +"\nTotal:\t\t\t" + Total
//               +"\n-------------"
              // +"\nDate:"+iDate 
             //  +"\nTime:" +iTime
               +"\n\n\n\n\n\nThanks for stay with Sopno Vubon"
               +"\nHave a happy and safe journey"       
       );
       
       
        
     
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnrec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtxtarearcip;
    // End of variables declaration//GEN-END:variables
}
