package src;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Baby
 */
public class Student_Form extends javax.swing.JInternalFrame {

    /**
     * Creates new form Student_Form
     */
    public Student_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbcls = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtroll = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsna = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BTNSAVE = new javax.swing.JButton();
        BTNSHOW = new javax.swing.JButton();
        btn = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setTitle("Student_Form");

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STUDENT FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("cls_id");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("class name");

        cmbcls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-class name--", "class6", "class7", "class8" }));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("student roll");

        txtroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrollActionPerformed(evt);
            }
        });

        jLabel4.setText("Student name");

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));

        BTNSAVE.setText("save");
        BTNSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSAVEActionPerformed(evt);
            }
        });

        BTNSHOW.setText("show");
        BTNSHOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSHOWActionPerformed(evt);
            }
        });

        btn.setText("BACK");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(BTNSAVE)
                .addGap(50, 50, 50)
                .addComponent(BTNSHOW)
                .addGap(34, 34, 34)
                .addComponent(btn)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNSAVE)
                    .addComponent(BTNSHOW)
                    .addComponent(btn))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 415, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsna, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtroll, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbcls, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtroll, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtsna, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcls, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSAVEActionPerformed
        // TODO add your handling code here:
        String stuna, clsna;
        stuna = txtsna.getText();
        clsna = cmbcls.getSelectedItem().toString();

        if (cmbcls.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, " plz select  clsname");
            cmbcls.requestFocus();
        }
//            model.addRow(new Object[]{clsname});
        Connection con = null;
        Statement stmt = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "123");
            stmt = con.createStatement();
            int count = 0;

            count = stmt.executeUpdate("insert into student8(studentname,nameofclass) values('" + stuna + "','" + clsna + "' )");
            if (count > 0) {
//                System.out.println("inserted successfully");
                JOptionPane.showMessageDialog(this, "inserted successfully");
//                clear();
//               displayInTable();
            } else {
//                System.out.println("insertion failed");
                JOptionPane.showMessageDialog(this, "insertion failed", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();

        }

    }//GEN-LAST:event_BTNSAVEActionPerformed

    private void BTNSHOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSHOWActionPerformed
        // TODO add your handling code here:

        getAllRecordShow();
        txtroll.requestFocus();
//         String stuna,clsna,sroll;
//        stuna =txtsna.getText();
//        clsna=cmbcls.getSelectedItem().toString();
//        
//          if(cmbcls.getSelectedIndex()==0){
//            JOptionPane.showMessageDialog(rootPane," plz select  clsname");
//            cmbcls.requestFocus();
//               Connection con = null;
//          Statement stmt = null;
//          ResultSet rs =null;
//           
//          
//        try {
//            
//            Class.forName("com.mysql.jdbc.Driver");
//               con =DriverManager.getConnection("jdbc:mysql://localhost:3306/student" , "root" , "123");
////            con = DBConnection.getDBConnection();
//            //Create the Statement object
//            stmt = con.createStatement();
//           // cls_id=Integer.parseInt(txtCLSID.getText());
//            //Execute the query
//            rs = stmt.executeQuery("select * from student8 where sroll= '" + txtroll.getText() + "' ");
//            //int count = 0;
//            while (rs.next()) {
//                //comcls.setText(rs.getString("nameofclass"));
//                txtsna.setText(rs.getString("studentname"));
//                cmbcls.setSelectedItem(rs.getString("clsna"));
//                //count++;
//            }
////            if (count == 0) {
////                JOptionPane.showMessageDialog(rootPane, "There is no such record");
////            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        } finally {
//            try {
//                //Close the connection and statement object
//                con.close();
//                stmt.close();
//            } catch (SQLException ex) {
//                System.out.println(ex);
//            }
//        }
//         
    }//GEN-LAST:event_BTNSHOWActionPerformed

    private void txtrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrollActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        new Firstpage().setVisible(true);
    }//GEN-LAST:event_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNSAVE;
    private javax.swing.JButton BTNSHOW;
    private javax.swing.JButton btn;
    private javax.swing.JComboBox<String> cmbcls;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtroll;
    private javax.swing.JTextField txtsna;
    // End of variables declaration//GEN-END:variables

    private void getAllRecordShow() {

        String stuna, clsna, sroll;
        stuna = txtsna.getText();
//        clsna = cmbcls.getSelectedItem().toString();
//        if (cmbcls.getSelectedIndex() == 0) {
//            JOptionPane.showMessageDialog(rootPane, " plz select  clsname");
//            cmbcls.requestFocus();
//        }
            Connection con = null;
            Statement stmt = null;
            ResultSet rs = null;

            try {

                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "123");
                con = DBConnection.getDBConnection();
                //Create the Statement object
                stmt = con.createStatement();
                //cls_id=Integer.parseInt(txtCLSID.getText());
                //Execute the query
                rs = stmt.executeQuery("select * from student8 where s_roll= '" + txtroll.getText() + "' ");
                int count = 0;
                while (rs.next()) {
                    //comcls.setText(rs.getString("nameofclass"));
                    txtsna.setText(rs.getString("studentname"));
                    //cmbcls.setSelectedItem(rs.getString("clsna"));
                    count++;
                }
                if (count == 0) {
                    JOptionPane.showMessageDialog(rootPane, "There is no such record");
                }

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    //Close the connection and statement object
                    con.close();
                    stmt.close();
                } catch (SQLException ex) {
                    System.out.println(ex);
                }

            }

    }
}
    
    
    
    
       

